receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :55678

exporters:
  jaeger/2:
    endpoint: localhost:14250
    insecure: true
  graylogkafka:
    brokers:
      - localhost:9092
    protocol_version: 2.0.0
    topic: otlp_spans
    encoding: fast_json
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200
processors:
  batch:

extensions:
  zpages:
    endpoint: 0.0.0.0:52679

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [graylogkafka, jaeger/2]
